// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface NewUrlRequest {
  url: string;
  short: string | null;
  user: string | null;
  expiry: string | null;
}
