// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicError } from './BasicError'
import type { BasicResponse } from './BasicResponse'

export type OidcCallbackResponseType =
  | BasicError
  | BasicError
  | BasicError
  | BasicError
  | BasicError
  | BasicError
  | BasicError
  | BasicError
  | BasicError
  | BasicResponse
  | BasicError
  | BasicError
  | BasicError
