// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicError } from "./BasicError";

export type OidcCallbackResponseType =
  | BasicError
  | BasicError
  | BasicError
  | BasicError
  | BasicError
  | BasicError
  | BasicError
  | BasicError
  | BasicError
  | string
  | BasicError
  | BasicError
  | BasicError;
