// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicError } from "./BasicError";

export type QrCodeResponse =
  | BasicError
  | BasicError
  | null
  | BasicError
  | BasicError
  | BasicError
  | number[]
  | number[]
  | number[];
