// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShortLink = {
  id: number
  url: string
  short_url: string
  original_url: string
  user_id?: string
  expiry_date?: string
  views: bigint
  created_at: string
  updated_at: string
}
