// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShortLink } from './ShortLink'

export type UserLinks = { urls: Array<ShortLink> }
