// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserView } from "./UserView";

export interface UserLinkWithViews {
  id: string;
  short_url: string;
  original_url: string;
  user_id: string;
  expiry_date?: string;
  created_at: string;
  updated_at: string;
  views: UserView[];
}
