// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UserView {
  id: number;
  headers?: Partial<Record<string, string[]>>;
  ip?: string;
  cache_hit: boolean;
  created_at: string;
}
