// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicError } from './BasicError'
import type { UserProfile } from './UserProfile'

export type UserProfileResponse = BasicError | BasicError | UserProfile
