// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserView = {
  id: number;
  headers?: { [key in string]?: Array<string> };
  ip?: string;
  cache_hit: boolean;
  created_at: string;
};
