// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicError } from "./BasicError";
import type { UserLink } from "./UserLink";
import type { UserLinksAndViews } from "./UserLinksAndViews";

export type UserLinksResponse =
  | BasicError
  | BasicError
  | UserLinksAndViews
  | Array<UserLink>;
