version = "0.1.0"
files = []

[package.entity]
version = "0.1.0"

[[package.entity.files]]
file = "libs/entity/Cargo.toml"
expr = 'version = "(.*)"'

[package.frontend]
version = "0.1.0"

[[package.frontend.files]]
file = "js/frontend/package.json"
expr = '"version": "(.*)",'

[package.micro-url]
version = "0.1.0"

[[package.micro-url.files]]
file = "apps/micro_url/Cargo.toml"
expr = 'version = "(.*)"'

[package.migration]
version = "0.1.0"

[[package.migration.files]]
file = "libs/migration/Cargo.toml"
expr = 'version = "(.*)"'

[package.server]
version = "0.1.0"

[[package.server.files]]
file = "apps/server/Cargo.toml"
expr = 'version = "(.*)"'
