//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub use super::{
    sessions::Entity as Sessions, short_link::Entity as ShortLink, user::Entity as User,
    user_pass::Entity as UserPass, views::Entity as Views,
};
