//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
    ts_rs :: TS,
)]
#[sea_orm(table_name = "views")]
#[ts(export)]
#[ts(export_to = "../../../js/frontend/src/lib/types/")]
#[ts(rename = "Views")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub short_link: i32,
    pub num_views: i32,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub headers: Option<Json>,
    pub ip_address: Option<String>,
    pub ip_location: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::location::Entity",
        from = "Column::IpLocation",
        to = "super::location::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Location,
    #[sea_orm(
        belongs_to = "super::short_link::Entity",
        from = "Column::ShortLink",
        to = "super::short_link::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ShortLink,
}

impl Related<super::location::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Location.def()
    }
}

impl Related<super::short_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShortLink.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
